spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/OmidZare1991/eureka-clients-configFile
          # "native" is used when the native profile is active, for local tests with a classpath repo:
#          search-paths: ConfigData
#        native:
#          search-locations: classpath:offline-repository/
server:
  port: 8001